In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/7817_1.csv")
df.head()

,id,asins,brand,categories,colors,dateAdded,dateUpdated,dimension,ean,keys,...,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username,sizes,upc,weight
0,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I initially had trouble deciding between the p...,"Paperwhite voyage, no regrets!",NaN,NaN,Cristina M,NaN,NaN,205 grams
1,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,Allow me to preface this with a little history...,One Simply Could Not Ask For More,NaN,NaN,Ricky,NaN,NaN,205 grams
2,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,4.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I am enjoying it so far. Great for reading. Ha...,Great for those that just want an e-reader,NaN,NaN,Tedd Gardiner,NaN,NaN,205 grams
3,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I bought one of the first Paperwhites and have...,Love / Hate relationship,NaN,NaN,Dougal,NaN,NaN,205 grams
4,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I have to say upfront - I don't like coroporat...,I LOVE IT,NaN,NaN,Miljan David Tanic,NaN,NaN,205 grams

In [3]:
df.shape

(1597, 27)

In [4]:
df.columns

Index(['id', 'asins', 'brand', 'categories', 'colors', 'dateAdded',
       'dateUpdated', 'dimension', 'ean', 'keys', 'manufacturer',
       'manufacturerNumber', 'name', 'prices', 'reviews.date',
       'reviews.doRecommend', 'reviews.numHelpful', 'reviews.rating',
       'reviews.sourceURLs', 'reviews.text', 'reviews.title',
       'reviews.userCity', 'reviews.userProvince', 'reviews.username', 'sizes',
       'upc', 'weight'],
      dtype='str')

In [5]:
df["reviews.text"].head()

0    I initially had trouble deciding between the p...
1    Allow me to preface this with a little history...
2    I am enjoying it so far. Great for reading. Ha...
3    I bought one of the first Paperwhites and have...
4    I have to say upfront - I don't like coroporat...
Name: reviews.text, dtype: str

In [6]:
df["reviews.text"].isnull().sum()

np.int64(0)

In [7]:
df["reviews.rating"].value_counts()

reviews.rating
5.0    741
4.0    236
3.0    124
1.0     42
2.0     34
Name: count, dtype: int64

In [8]:
df_clean = df[[
    "name",
    "brand",
    "categories",
    "reviews.rating",
    "reviews.text"
]]

In [9]:
df_clean.head()

,name,brand,categories,reviews.rating,reviews.text
0,Kindle Paperwhite,Amazon,"Amazon Devices,mazon.co.uk",5.0,I initially had trouble deciding between the p...
1,Kindle Paperwhite,Amazon,"Amazon Devices,mazon.co.uk",5.0,Allow me to preface this with a little history...
2,Kindle Paperwhite,Amazon,"Amazon Devices,mazon.co.uk",4.0,I am enjoying it so far. Great for reading. Ha...
3,Kindle Paperwhite,Amazon,"Amazon Devices,mazon.co.uk",5.0,I bought one of the first Paperwhites and have...
4,Kindle Paperwhite,Amazon,"Amazon Devices,mazon.co.uk",5.0,I have to say upfront - I don't like coroporat...

In [10]:
df_clean["name"].nunique()

62

In [11]:
product_reviews = df_clean.groupby("name")["reviews.text"].apply(" ".join).reset_index()

In [12]:
product_reviews.head()

,name,reviews.text
0,Alexa Voice Remote for Amazon Echo and Echo Dot,"As good as the Echo is, the Echo Voice Remote ..."
1,Alexa Voice Remote for Amazon Fire TV and Fire...,My fire stick (non voice activated) seemed to ...
2,All-New Amazon Fire 7 Tablet Case (7th Generation,"Over the years, I've tried a variety of cases ..."
3,All-New Amazon Fire HD 8 Tablet Case (7th Gene...,This is a good case that provides adequate pro...
4,All-New Amazon Fire TV Game Controller,"This is a great controller for our Fire TV, I ..."

In [13]:
product_reviews.shape

(62, 2)

In [14]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\alaga\onedrive\desktop\my script library\web 2\customer-behaviour-intelligence-system\.venv\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\alaga\onedrive\desktop\my script library\web 2\customer-behaviour-intelligence-system\.venv\lib\site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in c:\users\alaga\onedrive\desktop\my script library\web 2\customer-behaviour-intelligence-system\.venv\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\alaga\onedrive\desktop\my script library\web 2\customer-behaviour-intelligence-system\.venv\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\alaga\onedrive\desktop\my script library\web 2\customer-behaviour-intelligence-system\.venv\lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [16]:
tfidf = TfidfVectorizer(stop_words='english')

In [17]:
df.columns

Index(['id', 'asins', 'brand', 'categories', 'colors', 'dateAdded',
       'dateUpdated', 'dimension', 'ean', 'keys', 'manufacturer',
       'manufacturerNumber', 'name', 'prices', 'reviews.date',
       'reviews.doRecommend', 'reviews.numHelpful', 'reviews.rating',
       'reviews.sourceURLs', 'reviews.text', 'reviews.title',
       'reviews.userCity', 'reviews.userProvince', 'reviews.username', 'sizes',
       'upc', 'weight'],
      dtype='str')

In [18]:
review_vectors = tfidf.fit_transform(df['reviews.text'])

In [19]:
review_vectors.shape

(1597, 6195)

In [20]:
tfidf.get_feature_names_out()[:20]

array(['00', '000', '000s', '04', '07', '08', '0x0', '10', '100', '1000',
       '1000ma', '100mbps', '1024', '1080', '1080p', '10min', '10w', '11',
       '110', '119'], dtype=object)

In [21]:
from sklearn.metrics.pairwise import cosine_similarity

In [22]:
similarity_matrix = cosine_similarity(review_vectors)

In [23]:
similarity_matrix.shape

(1597, 1597)

In [24]:
similarity_matrix[0][:10]

array([1.        , 0.09253314, 0.10122375, 0.09515814, 0.15794446,
       0.00872108, 0.09253314, 0.08443236, 1.        , 0.10122375])

In [25]:
similarity_matrix[0]

array([1.        , 0.09253314, 0.10122375, ..., 0.08728211, 0.00918675,
       0.04327329], shape=(1597,))

In [26]:
similarity_scores = list(enumerate(similarity_matrix[0]))

In [27]:
similarity_scores = list(enumerate(similarity_matrix[0]))

In [28]:
sorted_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)

In [29]:
sorted_scores[:10]

[(0, np.float64(1.0000000000000002)),
 (8, np.float64(1.0000000000000002)),
 (263, np.float64(0.26302609606802824)),
 (254, np.float64(0.2536209725945116)),
 (279, np.float64(0.2536209725945116)),
 (737, np.float64(0.21220426471944714)),
 (740, np.float64(0.21220426471944714)),
 (743, np.float64(0.21220426471944714)),
 (746, np.float64(0.21220426471944714)),
 (778, np.float64(0.21220426471944714))]

In [30]:
df['reviews.text'].iloc[0]

"I initially had trouble deciding between the paperwhite and the voyage because reviews more or less said the same thing: the paperwhite is great, but if you have spending money, go for the voyage.Fortunately, I had friends who owned each, so I ended up buying the paperwhite on this basis: both models now have 300 ppi, so the 80 dollar jump turns out pricey the voyage's page press isn't always sensitive, and if you are fine with a specific setting, you don't need auto light adjustment).It's been a week and I am loving my paperwhite, no regrets! The touch screen is receptive and easy to use, and I keep the light at a specific setting regardless of the time of day. (In any case, it's not hard to change the setting either, as you'll only be changing the light level at a certain time of day, not every now and then while reading).Also glad that I went for the international shipping option with Amazon. Extra expense, but delivery was on time, with tracking, and I didnt need to worry about customs, which I may have if I used a third party shipping service."

In [31]:
df['reviews.text'].iloc[8]

"I initially had trouble deciding between the paperwhite and the voyage because reviews more or less said the same thing: the paperwhite is great, but if you have spending money, go for the voyage.Fortunately, I had friends who owned each, so I ended up buying the paperwhite on this basis: both models now have 300 ppi, so the 80 dollar jump turns out pricey the voyage's page press isn't always sensitive, and if you are fine with a specific setting, you don't need auto light adjustment).It's been a week and I am loving my paperwhite, no regrets! The touch screen is receptive and easy to use, and I keep the light at a specific setting regardless of the time of day. (In any case, it's not hard to change the setting either, as you'll only be changing the light level at a certain time of day, not every now and then while reading).Also glad that I went for the international shipping option with Amazon. Extra expense, but delivery was on time, with tracking, and I didnt need to worry about customs, which I may have if I used a third party shipping service."

In [32]:
top_similar_reviews = sorted_scores[1:6]

In [33]:
top_similar_reviews

[(8, np.float64(1.0000000000000002)),
 (263, np.float64(0.26302609606802824)),
 (254, np.float64(0.2536209725945116)),
 (279, np.float64(0.2536209725945116)),
 (737, np.float64(0.21220426471944714))]

In [34]:
for review in top_similar_reviews:
    print(df['reviews.text'].iloc[review[0]])
    print('Similarity Score:', review[1])
    print('-------------------')

I initially had trouble deciding between the paperwhite and the voyage because reviews more or less said the same thing: the paperwhite is great, but if you have spending money, go for the voyage.Fortunately, I had friends who owned each, so I ended up buying the paperwhite on this basis: both models now have 300 ppi, so the 80 dollar jump turns out pricey the voyage's page press isn't always sensitive, and if you are fine with a specific setting, you don't need auto light adjustment).It's been a week and I am loving my paperwhite, no regrets! The touch screen is receptive and easy to use, and I keep the light at a specific setting regardless of the time of day. (In any case, it's not hard to change the setting either, as you'll only be changing the light level at a certain time of day, not every now and then while reading).Also glad that I went for the international shipping option with Amazon. Extra expense, but delivery was on time, with tracking, and I didnt need to worry about customs, which I may have if I used a third party shipping service.
Similarity Score: 1.0000000000000002
-------------------
I'm a long time Kindle user, and have upgraded a number of times. Every upgrade was a significant improvement, and the Oasis continues that trend. I love my Voyage, but the Oasis makes it feel like a hardback book. The pictures and descriptions don't do the size and weight justice. Shockingly light, and small even with the case. Used without the case, it's like holding a few sheets of paper. Amazing. Haven't had it long enough to evaluate the battery life, but never had a problem with the previous models, so I assume the promise of much longer battery life (with the secondary battery in the case) is accurate.The balance in the hand without the case is stunningly good. With the case feels a bit like the Voyage (although quite a bit lighter than my Voyage in its case). Case is high quality and easy to put on and take off as needed. Screen seems a smidge clearer and higher definition than my Voyage (maybe due to the updated lighting system).I had the 'pressure sensitive' page turner option on my Voyage turned off. Much too jumpy and sensitive, even at its 'hard' setting. I won't miss that. The new mechanical buttons on the Oasis are AWESOME. Nice upgrade there, and nice to not have to touch the screen for the most part.Yes, it is pricey. I would say if you are a 'few hour a week' reader, the Paperwhite is your best bet (solid performance and very good price/value). But if you are a reading fanatic who reads a lot every day (like me!), the extra battery life and the balance/size/weight, along with the slightly improved screen is WELL worth the money, especially when spread over the life of the unit.Edit: A few more comments now that I've been using the Oasis for a number of months.Read more
Similarity Score: 0.26302609606802824
-------------------
Although I've owned almost every model of Kindle ebook readers since the 2nd generation Kindle that I bought in 2009, I had to think hard about ordering the new Voyage. I was very happy with my Paperwhite (the 2nd generation that was released in the fall of 2013), and as much as I wanted to try the Voyage, I wasn't sure I wanted to spend 199 on one. It became a moot point, though, when my wife ordered the Voyage, saying it was her early Christmas present to me. Now that I've had time to use the Voyage, I have to say I'm impressed. With hardware features like a 300 ppi display, LEDs that automatically adjust the screen brightness depending on the ambient lighting, and the user's choice of a touchscreen or sensors acting like buttons to turn pages, the Voyage is hands down the state-of-the-art e-ink ebook reader. At the end of my review, I'll give my opinion on whether it's worth upgrading from your current ebook reader.When I received the Voyage, the setup was quick (although you do have to go through a brief tutorial), and after downloading a few of my books from the Amazon Cloud and adjusting a few settings, the Voyage was ready to go. Here's a brief comparison of the Voyage and the Paperwhite:Voyage---------Size: 6.4x4.5x0.30Weight (wi-fi version): 6.3 ouncesDisplay: 6 diagonal, 300 pixels per inch, 16-level grayscale, LED frontlitStorage memory: 4GBPage turns: Touchscreen plus PagePressDisplay lighting: Adaptive light sensor (automatic) plus manual adjustmentPaperwhite-------------Size: 6.7x4.6x0.36Weight (wi-fi version): 7.Read more
Similarity Score: 0.2536209725945116
-------------------
Although I've owned almost every model of Kindle ebook readers since the 2nd generation Kindle that I bought in 2009, I had to think hard about ordering the new Voyage. I was very happy with my Paperwhite (the 2nd generation that was released in the fall of 2013), and as much as I wanted to try the Voyage, I wasn't sure I wanted to spend 199 on one. It became a moot point, though, when my wife ordered the Voyage, saying it was her early Christmas present to me. Now that I've had time to use the Voyage, I have to say I'm impressed. With hardware features like a 300 ppi display, LEDs that automatically adjust the screen brightness depending on the ambient lighting, and the user's choice of a touchscreen or sensors acting like buttons to turn pages, the Voyage is hands down the state-of-the-art e-ink ebook reader. At the end of my review, I'll give my opinion on whether it's worth upgrading from your current ebook reader.When I received the Voyage, the setup was quick (although you do have to go through a brief tutorial), and after downloading a few of my books from the Amazon Cloud and adjusting a few settings, the Voyage was ready to go. Here's a brief comparison of the Voyage and the Paperwhite:Voyage---------Size: 6.4x4.5x0.30Weight (wi-fi version): 6.3 ouncesDisplay: 6 diagonal, 300 pixels per inch, 16-level grayscale, LED frontlitStorage memory: 4GBPage turns: Touchscreen plus PagePressDisplay lighting: Adaptive light sensor (automatic) plus manual adjustmentPaperwhite-------------Size: 6.7x4.6x0.36Weight (wi-fi version): 7.Read more
Similarity Score: 0.2536209725945116
-------------------
This is the fifth e-ink Kindle reader that I've bought. My wife and I were early adopters of Kindle, and when we buy a new Kindle, the old one goes to the next niece or nephew in line. I loved the original Paperwhite, with its small size, touch screen, front-lighting, and virtual keyboard. The all-new Paperwhite is a definite step up, and for me, it was worth the move, but others will have to decide for themselves. If you read a lot, and you don't already have one of the newer e-ink Kindles, it's definitely worth upgrading to the Paperwhite. If you have the original Paperwhite, the upgrade is well worth considering. Although I've only had the new Paperwhite a few hours, I'm already glad I upgraded. Here's a summary of my initial impressions of the new Paperwhite.SIZE: It's the same size as the original Paperwhite - 6.7x4.6x0.36. The weight has been reduced slightly from 7.8 ounces to 7.3 ounces. The Paperwhite is very comfortable to hold in one hand, which is how I usually read. The really good news is that if you have a case for the original Paperwhite, it will also fit the new one (thank you, Amazon). If you buy a case, I highly recommend that the case include the magnetic AutoWake function. It's much easier to turn the Kindle on and off without fumbling for the small power switch.LIGHTING: The front-lighting is noticeably improved over the original Paperwhite, which had slightly visible shadows coming from the bottom edge where the LED lights were located. (It didn't bother me, but some readers were annoyed by that.) I couldn't see any shadows in the new Paperwhite, where the lighting appears brighter and more uniform. With the Paperwhite's front lighting, you'll never need a clip-on light, even in total darkness.Read more
Similarity Score: 0.21220426471944714
-------------------

In [35]:
for review in top_similar_reviews:
    index = review[0]
    score = review[1]

    print("Product:", df['name'].iloc[index])
    print("Review:", df['reviews.text'].iloc[index])
    print("Similarity Score:", score)
    print("-------------------")

Product: Kindle Paperwhite
Review: I initially had trouble deciding between the paperwhite and the voyage because reviews more or less said the same thing: the paperwhite is great, but if you have spending money, go for the voyage.Fortunately, I had friends who owned each, so I ended up buying the paperwhite on this basis: both models now have 300 ppi, so the 80 dollar jump turns out pricey the voyage's page press isn't always sensitive, and if you are fine with a specific setting, you don't need auto light adjustment).It's been a week and I am loving my paperwhite, no regrets! The touch screen is receptive and easy to use, and I keep the light at a specific setting regardless of the time of day. (In any case, it's not hard to change the setting either, as you'll only be changing the light level at a certain time of day, not every now and then while reading).Also glad that I went for the international shipping option with Amazon. Extra expense, but delivery was on time, with tracking, and I didnt need to worry about customs, which I may have if I used a third party shipping service.
Similarity Score: 1.0000000000000002
-------------------
Product: Kindle Oasis with Leather Charging Cover - Black
Review: I'm a long time Kindle user, and have upgraded a number of times. Every upgrade was a significant improvement, and the Oasis continues that trend. I love my Voyage, but the Oasis makes it feel like a hardback book. The pictures and descriptions don't do the size and weight justice. Shockingly light, and small even with the case. Used without the case, it's like holding a few sheets of paper. Amazing. Haven't had it long enough to evaluate the battery life, but never had a problem with the previous models, so I assume the promise of much longer battery life (with the secondary battery in the case) is accurate.The balance in the hand without the case is stunningly good. With the case feels a bit like the Voyage (although quite a bit lighter than my Voyage in its case). Case is high quality and easy to put on and take off as needed. Screen seems a smidge clearer and higher definition than my Voyage (maybe due to the updated lighting system).I had the 'pressure sensitive' page turner option on my Voyage turned off. Much too jumpy and sensitive, even at its 'hard' setting. I won't miss that. The new mechanical buttons on the Oasis are AWESOME. Nice upgrade there, and nice to not have to touch the screen for the most part.Yes, it is pricey. I would say if you are a 'few hour a week' reader, the Paperwhite is your best bet (solid performance and very good price/value). But if you are a reading fanatic who reads a lot every day (like me!), the extra battery life and the balance/size/weight, along with the slightly improved screen is WELL worth the money, especially when spread over the life of the unit.Edit: A few more comments now that I've been using the Oasis for a number of months.Read more
Similarity Score: 0.26302609606802824
-------------------
Product: Kindle Voyage E-reader
Review: Although I've owned almost every model of Kindle ebook readers since the 2nd generation Kindle that I bought in 2009, I had to think hard about ordering the new Voyage. I was very happy with my Paperwhite (the 2nd generation that was released in the fall of 2013), and as much as I wanted to try the Voyage, I wasn't sure I wanted to spend 199 on one. It became a moot point, though, when my wife ordered the Voyage, saying it was her early Christmas present to me. Now that I've had time to use the Voyage, I have to say I'm impressed. With hardware features like a 300 ppi display, LEDs that automatically adjust the screen brightness depending on the ambient lighting, and the user's choice of a touchscreen or sensors acting like buttons to turn pages, the Voyage is hands down the state-of-the-art e-ink ebook reader. At the end of my review, I'll give my opinion on whether it's worth upgrading from your current ebook reader.When I received the Voyage, the setup was quick (although you do have to go through a brief tutorial), and after downloading a few of my books from the Amazon Cloud and adjusting a few settings, the Voyage was ready to go. Here's a brief comparison of the Voyage and the Paperwhite:Voyage---------Size: 6.4x4.5x0.30Weight (wi-fi version): 6.3 ouncesDisplay: 6 diagonal, 300 pixels per inch, 16-level grayscale, LED frontlitStorage memory: 4GBPage turns: Touchscreen plus PagePressDisplay lighting: Adaptive light sensor (automatic) plus manual adjustmentPaperwhite-------------Size: 6.7x4.6x0.36Weight (wi-fi version): 7.Read more
Similarity Score: 0.2536209725945116
-------------------
Product: Certified Refurbished Kindle Voyage E-reader with Special Offers
Review: Although I've owned almost every model of Kindle ebook readers since the 2nd generation Kindle that I bought in 2009, I had to think hard about ordering the new Voyage. I was very happy with my Paperwhite (the 2nd generation that was released in the fall of 2013), and as much as I wanted to try the Voyage, I wasn't sure I wanted to spend 199 on one. It became a moot point, though, when my wife ordered the Voyage, saying it was her early Christmas present to me. Now that I've had time to use the Voyage, I have to say I'm impressed. With hardware features like a 300 ppi display, LEDs that automatically adjust the screen brightness depending on the ambient lighting, and the user's choice of a touchscreen or sensors acting like buttons to turn pages, the Voyage is hands down the state-of-the-art e-ink ebook reader. At the end of my review, I'll give my opinion on whether it's worth upgrading from your current ebook reader.When I received the Voyage, the setup was quick (although you do have to go through a brief tutorial), and after downloading a few of my books from the Amazon Cloud and adjusting a few settings, the Voyage was ready to go. Here's a brief comparison of the Voyage and the Paperwhite:Voyage---------Size: 6.4x4.5x0.30Weight (wi-fi version): 6.3 ouncesDisplay: 6 diagonal, 300 pixels per inch, 16-level grayscale, LED frontlitStorage memory: 4GBPage turns: Touchscreen plus PagePressDisplay lighting: Adaptive light sensor (automatic) plus manual adjustmentPaperwhite-------------Size: 6.7x4.6x0.36Weight (wi-fi version): 7.Read more
Similarity Score: 0.2536209725945116
-------------------
Product: Kindle Paperwhite
Review: This is the fifth e-ink Kindle reader that I've bought. My wife and I were early adopters of Kindle, and when we buy a new Kindle, the old one goes to the next niece or nephew in line. I loved the original Paperwhite, with its small size, touch screen, front-lighting, and virtual keyboard. The all-new Paperwhite is a definite step up, and for me, it was worth the move, but others will have to decide for themselves. If you read a lot, and you don't already have one of the newer e-ink Kindles, it's definitely worth upgrading to the Paperwhite. If you have the original Paperwhite, the upgrade is well worth considering. Although I've only had the new Paperwhite a few hours, I'm already glad I upgraded. Here's a summary of my initial impressions of the new Paperwhite.SIZE: It's the same size as the original Paperwhite - 6.7x4.6x0.36. The weight has been reduced slightly from 7.8 ounces to 7.3 ounces. The Paperwhite is very comfortable to hold in one hand, which is how I usually read. The really good news is that if you have a case for the original Paperwhite, it will also fit the new one (thank you, Amazon). If you buy a case, I highly recommend that the case include the magnetic AutoWake function. It's much easier to turn the Kindle on and off without fumbling for the small power switch.LIGHTING: The front-lighting is noticeably improved over the original Paperwhite, which had slightly visible shadows coming from the bottom edge where the LED lights were located. (It didn't bother me, but some readers were annoyed by that.) I couldn't see any shadows in the new Paperwhite, where the lighting appears brighter and more uniform. With the Paperwhite's front lighting, you'll never need a clip-on light, even in total darkness.Read more
Similarity Score: 0.21220426471944714
-------------------

In [97]:
def recommend_reviews(review_index):

    similarity_scores = list(enumerate(similarity_matrix[review_index]))

    sorted_scores = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )

    top_reviews = sorted_scores[1:6]

    for review in top_reviews:

        index = review[0]
        score = review[1]

        print("Product:", df['name'].iloc[index])
        print("Review:", df['reviews.text'].iloc[index])
        print("Similarity Score:", score)
        print("---------------------------")

In [37]:
df[['name', 'reviews.text']].head()

                name                                       reviews.text
0  Kindle Paperwhite  I initially had trouble deciding between the p...
1  Kindle Paperwhite  Allow me to preface this with a little history...
2  Kindle Paperwhite  I am enjoying it so far. Great for reading. Ha...
3  Kindle Paperwhite  I bought one of the first Paperwhites and have...
4  Kindle Paperwhite  I have to say upfront - I don't like coroporat...

In [94]:
df['name'].nunique()

62

In [39]:
product_reviews = df.groupby('name')['reviews.text'].apply(lambda x: ' '.join(x)).reset_index()

In [40]:
product_reviews.head()

,name,reviews.text
0,Alexa Voice Remote for Amazon Echo and Echo Dot,"As good as the Echo is, the Echo Voice Remote ..."
1,Alexa Voice Remote for Amazon Fire TV and Fire...,My fire stick (non voice activated) seemed to ...
2,All-New Amazon Fire 7 Tablet Case (7th Generation,"Over the years, I've tried a variety of cases ..."
3,All-New Amazon Fire HD 8 Tablet Case (7th Gene...,This is a good case that provides adequate pro...
4,All-New Amazon Fire TV Game Controller,"This is a great controller for our Fire TV, I ..."

In [41]:
product_reviews.shape

(62, 2)

In [43]:
product_reviews.columns = ['name', 'combined_reviews']

In [44]:
product_reviews.head()

,name,combined_reviews
0,Alexa Voice Remote for Amazon Echo and Echo Dot,"As good as the Echo is, the Echo Voice Remote ..."
1,Alexa Voice Remote for Amazon Fire TV and Fire...,My fire stick (non voice activated) seemed to ...
2,All-New Amazon Fire 7 Tablet Case (7th Generation,"Over the years, I've tried a variety of cases ..."
3,All-New Amazon Fire HD 8 Tablet Case (7th Gene...,This is a good case that provides adequate pro...
4,All-New Amazon Fire TV Game Controller,"This is a great controller for our Fire TV, I ..."

In [45]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [46]:
tfidf = TfidfVectorizer(stop_words='english')

In [47]:
tfidf_matrix = tfidf.fit_transform(product_reviews['combined_reviews'])

In [48]:
tfidf_matrix.shape

(62, 6195)

In [50]:
from sklearn.metrics.pairwise import cosine_similarity

In [51]:
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [52]:
cosine_sim.shape

(62, 62)

In [53]:
indices = pd.Series(product_reviews.index, index=product_reviews['name']).drop_duplicates()

In [54]:
indices.head()

name
Alexa Voice Remote for Amazon Echo and Echo Dot            0
Alexa Voice Remote for Amazon Fire TV and Fire TV Stick    1
All-New Amazon Fire 7 Tablet Case (7th Generation          2
All-New Amazon Fire HD 8 Tablet Case (7th Generation       3
All-New Amazon Fire TV Game Controller                     4
dtype: int64

In [55]:
product_reviews['name'].iloc[0]

'Alexa Voice Remote for Amazon Echo and Echo Dot'

In [56]:
indices['Alexa Voice Remote for Amazon Echo and Echo Dot']

np.int64(0)

In [58]:
sim_scores = list(enumerate(cosine_sim[0]))

In [59]:
sim_scores[:5]

[(0, np.float64(0.9999999999999997)),
 (1, np.float64(0.6254026692037269)),
 (2, np.float64(0.06819126455442308)),
 (3, np.float64(0.05873093910704716)),
 (4, np.float64(0.24506786476009682))]

In [61]:
sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

In [62]:
sim_scores[:10]

[(0, np.float64(0.9999999999999997)),
 (1, np.float64(0.6254026692037269)),
 (61, np.float64(0.5794502924538174)),
 (20, np.float64(0.3960608499019578)),
 (24, np.float64(0.2918305913421233)),
 (12, np.float64(0.2509314383401666)),
 (4, np.float64(0.24506786476009682)),
 (37, np.float64(0.23888877311175374)),
 (31, np.float64(0.2260252397671433)),
 (38, np.float64(0.2160151576189509))]

In [63]:
sim_scores = sim_scores[1:6]

In [64]:
product_indices = [i[0] for i in sim_scores]

In [65]:
product_indices

[1, 61, 20, 24, 12]

In [66]:
product_reviews['name'].iloc[product_indices]

1     Alexa Voice Remote for Amazon Fire TV and Fire...
61          Replacement Remote for Amazon Fire TV Stick
20                       Amazon Fire TV Game Controller
24    Amazon Tap - Alexa-Enabled Portable Bluetooth ...
12                                  Amazon Echo - Black
Name: name, dtype: str

In [93]:
def recommend_products(product_name, cosine_sim=cosine_sim):
    idx = indices[product_name]

    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    sim_scores = sim_scores[1:6]

    product_indices = [i[0] for i in sim_scores]

    return product_reviews['name'].iloc[product_indices]

In [71]:
recommend_products('Alexa Voice Remote for Amazon Echo and Echo Dot')

1     Alexa Voice Remote for Amazon Fire TV and Fire...
61          Replacement Remote for Amazon Fire TV Stick
20                       Amazon Fire TV Game Controller
24    Amazon Tap - Alexa-Enabled Portable Bluetooth ...
12                                  Amazon Echo - Black
Name: name, dtype: str

In [72]:
recommend_products('Alexa Voice Remote for Amazon Echo and Echo Dot').reset_index(drop=True)

0    Alexa Voice Remote for Amazon Fire TV and Fire...
1          Replacement Remote for Amazon Fire TV Stick
2                       Amazon Fire TV Game Controller
3    Amazon Tap - Alexa-Enabled Portable Bluetooth ...
4                                  Amazon Echo - Black
Name: name, dtype: str

In [73]:
product_reviews['name'].head(10)

0      Alexa Voice Remote for Amazon Echo and Echo Dot
1    Alexa Voice Remote for Amazon Fire TV and Fire...
2    All-New Amazon Fire 7 Tablet Case (7th Generation
3    All-New Amazon Fire HD 8 Tablet Case (7th Gene...
4               All-New Amazon Fire TV Game Controller
5    All-New Amazon Kid-Proof Case for Amazon Fire ...
6    All-New Amazon Kid-Proof Case for Amazon Fire ...
7                   All-New Fire 7 Kids Edition Tablet
8                     All-New Fire 7 Tablet with Alexa
9                All-New Fire HD 8 Kids Edition Tablet
Name: name, dtype: str

In [74]:
recommend_products('All-New Fire 7 Tablet with Alexa').reset_index(drop=True)

0    All-New Fire HD 8 Tablet with Alexa
1                     Kindle Fire HDX 7"
2                 Fire Tablet with Alexa
3           Fire HD 10 Tablet with Alexa
4                       Fire HD 7 Tablet
Name: name, dtype: str

In [75]:
recommend_products('Amazon Echo - Black').reset_index(drop=True)

0    Amazon Tap - Alexa-Enabled Portable Bluetooth ...
1                    Echo Dot (2nd Generation) - Black
2                                    Echo Show - Black
3      Alexa Voice Remote for Amazon Echo and Echo Dot
4    Certified Refurbished Echo Dot (2nd Generation...
Name: name, dtype: str

In [76]:
product_reviews.to_csv('processed_product_reviews.csv', index=False)

In [77]:
import os

os.path.exists('processed_product_reviews.csv')

True

In [78]:
import numpy as np

np.save('cosine_similarity_matrix.npy', cosine_sim)

In [79]:
# Install sentence-transformers if not installed
!pip install sentence-transformers

^C

In [92]:
from sentence_transformers import SentenceTransformer

bert_model = SentenceTransformer('all-MiniLM-L6-v2')

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1654.13it/s]

In [82]:
product_texts = product_reviews['combined_reviews'].tolist()

bert_embeddings = bert_model.encode(product_texts, show_progress_bar=True)

bert_embeddings.shape

Batches: 100%|██████████| 2/2 [00:10<00:00,  5.45s/it]

(62, 384)

In [83]:
from sklearn.metrics.pairwise import cosine_similarity

In [84]:
bert_similarity = cosine_similarity(bert_embeddings)

In [86]:
def get_bert_recommendations(product_name, top_n=5):
    product_index = product_reviews[
        product_reviews['name'].str.lower() == product_name.lower()
    ].index[0]

    similarity_scores = list(enumerate(bert_similarity[product_index]))

    sorted_scores = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )

    top_products = sorted_scores[1:top_n+1]

    recommended_indices = [i[0] for i in top_products]

    return product_reviews[['name']].iloc[recommended_indices]

In [87]:
get_bert_recommendations("Fire HD 8 Tablet with Alexa")

                                       name
42                         Fire HD 8 Tablet
32  Certified Refurbished Fire HD 10 Tablet
41                         Fire HD 7 Tablet
8          All-New Fire 7 Tablet with Alexa
40                         Fire HD 6 Tablet

In [90]:
bert_recommendations = get_bert_recommendations("Fire HD 8 Tablet with Alexa")
bert_recommendations

                                       name
42                         Fire HD 8 Tablet
32  Certified Refurbished Fire HD 10 Tablet
41                         Fire HD 7 Tablet
8          All-New Fire 7 Tablet with Alexa
40                         Fire HD 6 Tablet

In [100]:
def get_tfidf_recommendations(product_name, top_n=5):
    product_index = product_reviews[
        product_reviews['name'].str.lower() == product_name.lower()
    ].index[0]

    similarity_scores = list(enumerate(cosine_sim[product_index]))

    sorted_scores = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )

    top_products = sorted_scores[1:top_n+1]

    recommended_indices = [i[0] for i in top_products]

    return product_reviews[['name']].iloc[recommended_indices]

In [102]:
tfidf_recommendations = get_tfidf_recommendations("Fire HD 8 Tablet with Alexa")
tfidf_recommendations

                      name
42        Fire HD 8 Tablet
50      Kindle Fire HDX 7"
46  Fire Tablet with Alexa
41        Fire HD 7 Tablet
40        Fire HD 6 Tablet

In [103]:
hybrid_similarity = (cosine_sim + bert_similarity) / 2

In [111]:
def recommend_products_hybrid(product_name, top_n=5):
    # find products that contain the text
    matches = df[
        df["name"].str.lower().str.contains(product_name.lower(), na=False)
    ]

    # if no product is found
    if len(matches) == 0:
        return "Product not found. Try another product name."

    # use the first matching product
    product_index = matches.index[0]

    # get hybrid similarity scores
    similarity_scores = list(enumerate(hybrid_similarity[product_index]))

    # sort scores
    similarity_scores = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )

    # remove same product
    similarity_scores = similarity_scores[1:top_n + 1]

    # get indexes
    recommended_indexes = [i[0] for i in similarity_scores]

    return df.iloc[recommended_indexes][["name"]]

In [115]:
df = df.reset_index(drop=True)

In [116]:
def recommend_products_hybrid(product_name, top_n=5):
    matches = df[
        df["name"].str.lower().str.contains(product_name.lower(), na=False)
    ]

    if len(matches) == 0:
        return "Product not found. Try another product name."

    product_position = matches.index[0]

    similarity_scores = list(enumerate(hybrid_similarity[product_position]))

    similarity_scores = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )

    similarity_scores = similarity_scores[1:top_n + 1]

    recommended_positions = [i[0] for i in similarity_scores]

    return df.iloc[recommended_positions][["name"]]

In [117]:
recommend_products_hybrid("Fire Tablet", top_n=5)

IndexError: index 454 is out of bounds for axis 0 with size 62